### ISSUE TITLE
Current ToDo List

### ISSUE THREAD

**Issue by Vodes** [Vodes/vodesfunc#1]
For first public release:

- [x] Chapters XML/TXT input option / parsing
- [x] Better handling of workdirs (making `Setup` globally accessible and force "disposing" of it first if existing)
- [x] x264 & FFV1 Support 
- [x] `settings_builder` for x264
- [x] Muxing of timecode files
- [x] Add CRC32 support in the muxing (via naming template, was requested)

After:

- [ ] Setting Builder presets maybe?
- [ ] resumable encodes
- [ ] x264/265 external settings file support
- [ ] Support AudioNode input for `encode_audio` (waiting on vapoursynth upstream)

Probably never:

- [x] ~~Completely overhaul font collector (mostly not my code and also just awful to work with)~~
- [ ] Use [this](https://github.com/moi15moi/FontCollector) for most of the lifting needed for fonts 

No particular priority.

**Comment by Vodes** [comment]
A few people mentioned that it would be far more convenient for the automation stuff to be a separate package; mostly to avoid a Vapoursynth dependency.

This will also bring at least a minor refactor of the entire automation suite.

I'm not quite sure yet when or if I'll do this but this is how I envisioned it:
- Move all automation code that doesn't need Vapoursynth to a new package
- Restore Vapoursynth related functionality in this package by extending existing classes from the new package
- Passthrough imports from the new package to this one to avoid major breakage in existing scripts using vodesfunc

**Comment by Vodes** [comment]
All of this is essentially implemented or improved at [vs-muxtools](/Irrational-Encoding-Wizardry/vs-muxtools) and [muxtools](/Irrational-Encoding-Wizardry/muxtools).
